### ISSUE TITLE
Error on Heroku

### ISSUE THREAD

**Issue by miquellaboria** [joslynesser/mongo-twitter-streaming#1]
Hi, 

I push the code to heroku with:

heroku create
heroku addons:add mongohq:free
heroku config:add TWITTER_USERNAME=username
heroku config:add TWITTER_PASSWORD=password
git push heroku

When I execute the url appears: Application Error
On the log: Error H10 (App crashed) -> GET stormy-window-7935.heroku.com/ dyno= queue= wait= service= status=503 bytes=

Can you help me?

Thank you!

**Comment by ShriramK** [comment]
Most probably server call dropped and/or  didn't send valid data as response
